# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        local_public_adapter:
            local:
                location: '%kernel.project_dir%/var/public'

        local_temp_adapter:
            local:
                location: '%kernel.project_dir%/var/temp'
        s3.dinner_date.public_media_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: dinner-date-media-public
                options:
                    ACL: 'public-read'
    filesystems:
        local_public_filesystem:
            adapter: local_public_adapter
            alias: League\Flysystem\Filesystem
        local_temp_filesystem:
            adapter: local_temp_adapter
            alias: League\Flysystem\Filesystem
        s3_public_media_filesystem:
            adapter: s3.dinner_date.public_media_adapter
            alias: League\Flysystem\Filesystem
