INSERT INTO country (name, alpha_2, alpha_3) VALUES
('Afghanistan','af','afg'),
('Albania','al','alb'),
('Algeria','dz','dza'),
('Andorra','ad','and'),
('Angola','ao','ago'),
('Antigua and Barbuda','ag','atg'),
('Argentina','ar','arg'),
('Armenia','am','arm'),
('Australia','au','aus'),
('Austria','at','aut'),
('Azerbaijan','az','aze'),
('Bahamas','bs','bhs'),
('Bahrain','bh','bhr'),
('Bangladesh','bd','bgd'),
('Barbados','bb','brb'),
('Belarus','by','blr'),
('Belgium','be','bel'),
('Belize','bz','blz'),
('Benin','bj','ben'),
('Bhutan','bt','btn'),
('Bolivia (Plurinational State of)','bo','bol'),
('Bosnia and Herzegovina','ba','bih'),
('Botswana','bw','bwa'),
('Brazil','br','bra'),
('Brunei Darussalam','bn','brn'),
('Bulgaria','bg','bgr'),
('Burkina Faso','bf','bfa'),
('Burundi','bi','bdi'),
('Cabo Verde','cv','cpv'),
('Cambodia','kh','khm'),
('Cameroon','cm','cmr'),
('Canada','ca','can'),
('Central African Republic','cf','caf'),
('Chad','td','tcd'),
('Chile','cl','chl'),
('China','cn','chn'),
('Colombia','co','col'),
('Comoros','km','com'),
('Congo','cg','cog'),
('Congo, Democratic Republic of the','cd','cod'),
('Costa Rica','cr','cri'),
('Côte dIvoire','ci','civ'),
('Croatia','hr','hrv'),
('Cuba','cu','cub'),
('Cyprus','cy','cyp'),
('Czechia','cz','cze'),
('Denmark','dk','dnk'),
('Djibouti','dj','dji'),
('Dominica','dm','dma'),
('Dominican Republic','do','dom'),
('Ecuador','ec','ecu'),
('Egypt','eg','egy'),
('El Salvador','sv','slv'),
('Equatorial Guinea','gq','gnq'),
('Eritrea','er','eri'),
('Estonia','ee','est'),
('Eswatini','sz','swz'),
('Ethiopia','et','eth'),
('Fiji','fj','fji'),
('Finland','fi','fin'),
('France','fr','fra'),
('Gabon','ga','gab'),
('Gambia','gm','gmb'),
('Georgia','ge','geo'),
('Germany','de','deu'),
('Ghana','gh','gha'),
('Greece','gr','grc'),
('Grenada','gd','grd'),
('Guatemala','gt','gtm'),
('Guinea','gn','gin'),
('Guinea-Bissau','gw','gnb'),
('Guyana','gy','guy'),
('Haiti','ht','hti'),
('Honduras','hn','hnd'),
('Hungary','hu','hun'),
('Iceland','is','isl'),
('India','in','ind'),
('Indonesia','id','idn'),
('Iran (Islamic Republic of)','ir','irn'),
('Iraq','iq','irq'),
('Ireland','ie','irl'),
('Israel','il','isr'),
('Italy','it','ita'),
('Jamaica','jm','jam'),
('Japan','jp','jpn'),
('Jordan','jo','jor'),
('Kazakhstan','kz','kaz'),
('Kenya','ke','ken'),
('Kiribati','ki','kir'),
('Korea (Democratic Peoples Republic of)','kp','prk'),
 ('Korea, Republic of','kr','kor'),
 ('Kuwait','kw','kwt'),
 ('Kyrgyzstan','kg','kgz'),
 ('Lao Peoples Democratic Republic','la','lao'),
('Latvia','lv','lva'),
('Lebanon','lb','lbn'),
('Lesotho','ls','lso'),
('Liberia','lr','lbr'),
('Libya','ly','lby'),
('Liechtenstein','li','lie'),
('Lithuania','lt','ltu'),
('Luxembourg','lu','lux'),
('Madagascar','mg','mdg'),
('Malawi','mw','mwi'),
('Malaysia','my','mys'),
('Maldives','mv','mdv'),
('Mali','ml','mli'),
('Malta','mt','mlt'),
('Marshall Islands','mh','mhl'),
('Mauritania','mr','mrt'),
('Mauritius','mu','mus'),
('Mexico','mx','mex'),
('Micronesia (Federated States of)','fm','fsm'),
('Moldova, Republic of','md','mda'),
('Monaco','mc','mco'),
('Mongolia','mn','mng'),
('Montenegro','me','mne'),
('Morocco','ma','mar'),
('Mozambique','mz','moz'),
('Myanmar','mm','mmr'),
('Namibia','na','nam'),
('Nauru','nr','nru'),
('Nepal','np','npl'),
('Netherlands','nl','nld'),
('New Zealand','nz','nzl'),
('Nicaragua','ni','nic'),
('Niger','ne','ner'),
('Nigeria','ng','nga'),
('North Macedonia','mk','mkd'),
('Norway','no','nor'),
('Oman','om','omn'),
('Pakistan','pk','pak'),
('Palau','pw','plw'),
('Panama','pa','pan'),
('Papua New Guinea','pg','png'),
('Paraguay','py','pry'),
('Peru','pe','per'),
('Philippines','ph','phl'),
('Poland','pl','pol'),
('Portugal','pt','prt'),
('Qatar','qa','qat'),
('Romania','ro','rou'),
('Russian Federation','ru','rus'),
('Rwanda','rw','rwa'),
('Saint Kitts and Nevis','kn','kna'),
('Saint Lucia','lc','lca'),
('Saint Vincent and the Grenadines','vc','vct'),
('Samoa','ws','wsm'),
('San Marino','sm','smr'),
('Sao Tome and Principe','st','stp'),
('Saudi Arabia','sa','sau'),
('Senegal','sn','sen'),
('Serbia','rs','srb'),
('Seychelles','sc','syc'),
('Sierra Leone','sl','sle'),
('Singapore','sg','sgp'),
('Slovakia','sk','svk'),
('Slovenia','si','svn'),
('Solomon Islands','sb','slb'),
('Somalia','so','som'),
('South Africa','za','zaf'),
('South Sudan','ss','ssd'),
('Spain','es','esp'),
('Sri Lanka','lk','lka'),
('Sudan','sd','sdn'),
('Suriname','sr','sur'),
('Sweden','se','swe'),
('Switzerland','ch','che'),
('Syrian Arab Republic','sy','syr'),
('Tajikistan','tj','tjk'),
('Tanzania, United Republic of','tz','tza'),
('Thailand','th','tha'),
('Timor-Leste','tl','tls'),
('Togo','tg','tgo'),
('Tonga','to','ton'),
('Trinidad and Tobago','tt','tto'),
('Tunisia','tn','tun'),
('Turkey','tr','tur'),
('Turkmenistan','tm','tkm'),
('Tuvalu','tv','tuv'),
('Uganda','ug','uga'),
('Ukraine','ua','ukr'),
('United Arab Emirates','ae','are'),
('United Kingdom of Great Britain and Northern Ireland','gb','gbr'),
('United States of America','us','usa'),
('Uruguay','uy','ury'),
('Uzbekistan','uz','uzb'),
('Vanuatu','vu','vut'),
('Venezuela (Bolivarian Republic of)','ve','ven'),
('Viet Nam','vn','vnm'),
('Yemen','ye','yem'),
('Zambia','zm','zmb'),
('Zimbabwe','zw','zwe');